# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d73bc918837e31e3d45291ac0289ad9"
name = "Order Funnel"
application_url = "https://taxes-persian-offline-incoming.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-84da0cc9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_fulfillments,write_orders"

[auth]
redirect_urls = [
  "https://taxes-persian-offline-incoming.trycloudflare.com/auth/callback",
  "https://taxes-persian-offline-incoming.trycloudflare.com/auth/shopify/callback",
  "https://taxes-persian-offline-incoming.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false
