# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d73bc918837e31e3d45291ac0289ad9"
name = "Order Funnel"
application_url = "https://nails-scientists-industrial-treat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "order-funnel.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://nails-scientists-industrial-treat.trycloudflare.com/auth/callback",
  "https://nails-scientists-industrial-treat.trycloudflare.com/auth/shopify/callback",
  "https://nails-scientists-industrial-treat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
